'use strict';
const HEADER = `'use strict';
/* BEGIN LPC SPRITE MANIFEST — describes art/sprites/*.png: third-party art,
   OGA-BY 3.0, NOT under index.html's licence. See LICENSE part 2 and
   art/CREDITS.md.

   Generated by tools/build-sprites.mjs. Do not edit by hand: the rects in
   here describe the pixels in those PNGs, and the two are only ever correct
   together — which is also why each sheet carries a hash of its own bytes
   as a cache key.

   A script rather than JSON, and loaded rather than fetched, because that is
   what keeps the game opening from file:// — see CLAUDE.md. */
`;

export function renderManifest(sheets) {
  const atlas = { sheets };
  return HEADER + `const SPRITE_ATLAS = ${JSON.stringify(atlas)};\n` + '/* END LPC SPRITE MANIFEST */\n';
}
